### ISSUE TITLE
Create bot singleton without service dependency?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-core#45] opened 2020-08-26 03:50 UTC
Currently I am creating a Discord adapter using Composer for fun here https://github.com/xieofxie/BotFramework-Discord
Discord has a websocket based API, so current C# SDK is based on a singleton client https://github.com/discord-net/Discord.Net

I noticed that we create a singleton Bot in Composer now, however it depends on several services which could not be created separately. https://github.com/xieofxie/BotFramework-Discord/blob/becfb8ee695e398c8dbbe9391a808e932e7e8831/runtime/azurewebapp/Startup.cs#L187
(See `s.GetService<BotFrameworkClient>()` and `s.GetService<IBotTelemetryClient>()`)

So I have to load a page to start the Discord client to get the bot singleton.
Is there any other way to solve this? Thanks!

**Comment by peterinnesmsft** [comment] 2020-12-01 19:44
@xieofxie after having discussed with the team, we are going to close this issue with no further action.

As I understand the issue, the real ask here is to minimize the cold start time caused by service initialization on incoming requests. We do not intend to use a pattern of directly instantiating instances of classes that will be registered with IServiceCollection, as it increases the chances of causing complex initialization chains that are otherwise avoided precisely by using DI/IoC patterns correctly. Additionally, with the approach we are taking with the runtime, we don't expect users will directly have the code that manages the registration of the runtime-required services - these will be abstracted away behind an extension method on the service collection.

In an individual developer's case, should they have need to instantiate registered services during Startup, they can create a ServiceProvider from a ServiceCollection and use this to create instances in a limited scope that can be cleaned up when appropriate. There are also other mechanisms, such as healthcheck/ping endpoints or internal background threads, that could be used to warm services without the need to wait for incoming requests.

That said, we don't have strong data or metrics to indicate that this is a widespread problem. If we have data to suggest this is something that is actively being asked for from our customers, then we can review again accordingly, but for now, we have no intention to take this any further.

Let me know if you have any questions.

**Closed by peterinnesmsft** 2020-12-01 19:44 UTC
Labels: Area: Runtime
